from pathlib import Path
import re

GNOST_START = "<!-- GNOST:ONBOARDING:START -->"
GNOST_END = "<!-- GNOST:ONBOARDING:END -->"

GNOST_BLOCK = f"""{GNOST_START}

## Onboarding
This repository includes an **auto-generated onboarding guide**

[![Onboarding](https://img.shields.io/badge/onboarding-ONBOARD.md-cyan)](./ONBOARD.md)

Generated by <a href="https://gnost.readthedocs.io">GNOST</a> to help understand the codebase.

{GNOST_END}
"""


class ReadmeInjector:
    """
    Safely injects or updates a GNOST-managed onboarding block in README.md
    """

    def __init__(self, root: str):
        self.readme_path = Path(root) / "README.md"

    # -------------------------
    # Public API
    # -------------------------

    def inject(self) -> bool:
        """
        Inject or update onboarding block.

        Returns:
            True  -> README modified
            False -> README missing
        """
        if not self.readme_path.exists():
            return False

        content = self.readme_path.read_text(encoding="utf-8")

        # Case 1: GNOST block already exists → update
        if GNOST_START in content and GNOST_END in content:
            updated = self._update_block(content)
            self.readme_path.write_text(updated, encoding="utf-8")
            return True

        # Case 2: Inject new block
        injected = self._inject_before_h2_or_append(content)
        self.readme_path.write_text(injected, encoding="utf-8")
        return True

    # -------------------------
    # Internal helpers
    # -------------------------

    def _update_block(self, content: str) -> str:
        return re.sub(
            rf"{GNOST_START}.*?{GNOST_END}",
            GNOST_BLOCK,
            content,
            flags=re.DOTALL,
        )

    def _inject_before_h2_or_append(self, content: str) -> str:
        """
        Insert GNOST block before the first H2 (##) heading.
        If no H2 exists, append to the end of the README.
        """
        lines = content.splitlines()

        for i, line in enumerate(lines):
            # Detect H2 heading (## but not ###)
            if line.startswith("## ") and not line.startswith("###"):
                return "\n".join(lines[:i] + [""] + [GNOST_BLOCK] + [""] + lines[i:])

        # No H2 found → append at end
        return content.rstrip() + "\n\n" + GNOST_BLOCK + "\n"
